server:
  port: 8082

healthcare:
  kafka:
    enabled: true
    encounter-topic: healthcare.encounter.created
    ai-workflow-topic: ai.symptom.query

spring:
  application:
    name: triage-service
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: healthcare-triage-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.healthcare.triage.model.PatientEncounterMessage
        spring.json.use.type.headers: false
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add.type.headers: false
    listener:
      missing-topics-fatal: false
