server:
  port: 8085

spring:
  application:
    name: practitioner-service
  datasource:
    url: jdbc:postgresql://localhost:5432/healthcare
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
