server:
  port: 8080

healthcare:
  kafka:
    enabled: true
    symptom-query-topic: ai.symptom.query
    symptom-result-topic: ai.symptom.result

spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: healthcare-backend
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.healthcare.model.AiSymptomResultMessage
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      missing-topics-fatal: false
